[pytest]
testpaths = tests
addopts = --strict-config --strict-markers
timeout = 60
timeout_method = thread
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated
    ignore::authlib.deprecate.AuthlibDeprecationWarning
