#!/usr/bin/env python3
"""Generate deterministic kebele staging SQL and a parent-match review report."""

import argparse
import csv
import io
import re
from collections import Counter, defaultdict
from pathlib import Path


def normalize_admin_code(value: str, width: int) -> str | None:
    raw = value.strip().upper()
    digits = raw.removeprefix("ET")
    return f"ET{digits.zfill(width)}" if digits.isdigit() else None


def normalize_kebele_code(value: str) -> str | None:
    raw = value.strip()
    return f"ET{raw.zfill(12)}" if raw.isdigit() else None


def sql_text(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def existing_geography(location_sql: str):
    regions = set(re.findall(r"INSERT INTO g2p_region .*? SELECT '([^']+)'", location_sql))
    zones = set(re.findall(r"INSERT INTO g2p_zone .*? SELECT '([^']+)'", location_sql))
    woredas = set(re.findall(r"INSERT INTO g2p_woreda .*? SELECT '([^']+)'", location_sql))
    return regions, zones, woredas


def read_csv(path: Path):
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def choose_reference_woredas(kebele_rows, reference_rows, existing_woredas):
    needed = defaultdict(list)
    for row in kebele_rows:
        code = normalize_admin_code(row["woreda"], 6)
        if code and len(code) == 8 and code not in existing_woredas:
            needed[code].append(normalize_admin_code(row["zone"], 4))

    candidates = defaultdict(list)
    for row in reference_rows:
        code = normalize_admin_code(row["Code"], 6)
        candidates[code].append(
            {
                "name": row["Woreda"].strip(),
                "zone_code": normalize_admin_code(row["Zone/Code"], 4),
                "zone_name": row["Zone"].strip(),
                "region_name": row["Zone/Region"].strip(),
            }
        )

    selected = {}
    for code, source_zones in needed.items():
        matching = [item for item in candidates.get(code, []) if item["zone_code"] in set(source_zones)]
        unique = {
            (
                item["name"].casefold(),
                item["zone_code"],
                item["zone_name"].casefold(),
                item["region_name"].casefold(),
            ): item
            for item in matching
        }
        if len(unique) == 1:
            selected[code] = next(iter(unique.values()))
    return selected


def build_seed(kebele_path: Path, woreda_path: Path, location_path: Path):
    kebele_rows = read_csv(kebele_path)
    reference_rows = read_csv(woreda_path)
    regions, existing_zones, existing_woredas = existing_geography(location_path.read_text(encoding="utf-8"))
    selected_woredas = choose_reference_woredas(kebele_rows, reference_rows, existing_woredas)

    missing_zones = {}
    for item in selected_woredas.values():
        zone_code = item["zone_code"]
        if zone_code not in existing_zones:
            missing_zones[zone_code] = item["zone_name"]
    for zone_code in missing_zones:
        region_code = f"ET{zone_code[2:4]}"
        if region_code not in regions:
            raise ValueError(f"Missing parent region {region_code} for {zone_code}")

    statements = [
        "-- Generated by scripts/kebele/generate_seed_sql.py; do not edit by hand.",
        "BEGIN;",
    ]
    for zone_code, zone_name in sorted(missing_zones.items()):
        region_code = f"ET{zone_code[2:4]}"
        statements.append(
            "INSERT INTO g2p_zone "
            "(code, name, admin2_pcod, admin2_refn, region) "
            f"SELECT {sql_text(zone_code)}, {sql_text(zone_name)}, "
            f"{sql_text(zone_code)}, {sql_text(zone_name)}, region.id "
            "FROM g2p_region region "
            f"WHERE region.code = {sql_text(region_code)} "
            f"AND NOT EXISTS (SELECT 1 FROM g2p_zone WHERE code = {sql_text(zone_code)});"
        )
    for woreda_code, item in sorted(selected_woredas.items()):
        statements.append(
            "INSERT INTO g2p_woreda "
            "(code, name, admin3_pcod, admin3_refn, zone) "
            f"SELECT {sql_text(woreda_code)}, {sql_text(item['name'])}, "
            f"{sql_text(woreda_code)}, {sql_text(item['name'])}, zone.id "
            "FROM g2p_zone zone "
            f"WHERE zone.code = {sql_text(item['zone_code'])} "
            f"AND NOT EXISTS (SELECT 1 FROM g2p_woreda WHERE code = {sql_text(woreda_code)});"
        )

    available_woredas = existing_woredas | set(selected_woredas)
    review_rows = []
    insert_rows = []
    seen_codes = set()
    for source_row_number, row in enumerate(kebele_rows, start=2):
        code = normalize_kebele_code(row["name"])
        if code is None:
            if row["name"].strip().casefold() == "other":
                continue
            raise ValueError(f"Invalid kebele code on CSV row {source_row_number}")
        if code in seen_codes:
            raise ValueError(f"Duplicate normalized kebele code: {code}")
        seen_codes.add(code)

        source_woreda = row["woreda"].strip()
        normalized_woreda = normalize_admin_code(source_woreda, 6)
        matched_woreda = None
        method = "UNRESOLVED"
        status = "UNRESOLVED"
        note = "Woreda code was not found in the current or reviewed reference data"

        if normalized_woreda in existing_woredas:
            matched_woreda = normalized_woreda
            method = "EXACT_WOREDA_CODE"
            status = "MATCHED"
            note = None
        elif normalized_woreda in selected_woredas:
            matched_woreda = normalized_woreda
            method = "WOREDA_REFERENCE"
            status = "MATCHED"
            note = "Woreda and any missing zone were added from woreda_data.csv"
        elif source_woreda.casefold() == "e":
            derived = f"ET{code[2:8]}"
            if derived in available_woredas:
                matched_woreda = derived
                method = "REVIEWED_CODE_HIERARCHY"
                status = "MATCHED"
                note = "Malformed source woreda 'e' resolved from kebele code and source zone"
        elif normalized_woreda == "ET101009":
            matched_woreda = "ET070306"
            method = "REVIEWED_CROSSWALK"
            status = "MATCHED"
            note = "Doyogena rows mapped to ET070306 using source zone ET0703 and woreda reference"

        insert_rows.append(
            (
                code,
                row["label"].strip(),
                row["name"].strip(),
                row["region"].strip() or None,
                row["zone"].strip() or None,
                source_woreda or None,
                matched_woreda,
                method,
                status,
                note,
            )
        )
        review_rows.append(
            {
                "source_row_number": source_row_number,
                "kebele_code": code,
                "display_name": row["label"].strip(),
                "source_region_code": row["region"].strip(),
                "source_zone_code": row["zone"].strip(),
                "source_woreda_code": source_woreda,
                "matched_woreda_code": matched_woreda or "",
                "match_method": method,
                "match_status": status,
                "review_note": note or "",
            }
        )

    columns = (
        "code, display_name, source_code, source_region_code, source_zone_code, "
        "source_woreda_code, matched_woreda_code, match_method, match_status, review_note"
    )
    for offset in range(0, len(insert_rows), 500):
        values = []
        for item in insert_rows[offset : offset + 500]:
            values.append("(" + ", ".join(sql_text(value) for value in item) + ")")
        statements.append(f"INSERT INTO g2p_kebele ({columns}) VALUES\n  " + ",\n  ".join(values) + ";")
    statements.append("COMMIT;")
    sql_output = "\n".join(statements) + "\n"

    report = io.StringIO(newline="")
    writer = csv.DictWriter(report, fieldnames=list(review_rows[0]))
    writer.writeheader()
    writer.writerows(review_rows)
    counts = Counter(row["match_method"] for row in review_rows)
    report_output = report.getvalue().replace("\r\n", "\n")
    return sql_output, report_output, counts, len(missing_zones), len(selected_woredas)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("kebele_csv", type=Path)
    parser.add_argument("woreda_csv", type=Path)
    parser.add_argument("location_sql", type=Path)
    parser.add_argument("output_sql", type=Path)
    parser.add_argument("--review-output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sql_output, report_output, counts, zone_count, woreda_count = build_seed(
        args.kebele_csv, args.woreda_csv, args.location_sql
    )
    if args.check:
        if args.output_sql.read_text(encoding="utf-8") != sql_output:
            raise SystemExit("Generated kebele SQL is out of date")
        if args.review_output.read_text(encoding="utf-8") != report_output:
            raise SystemExit("Generated kebele review report is out of date")
    else:
        args.output_sql.write_text(sql_output, encoding="utf-8")
        args.review_output.parent.mkdir(parents=True, exist_ok=True)
        args.review_output.write_text(report_output, encoding="utf-8")
    print(
        f"kebeles={sum(counts.values())} methods={dict(sorted(counts.items()))} "
        f"added_zones={zone_count} added_woredas={woreda_count}"
    )


if __name__ == "__main__":
    main()
